### ISSUE TITLE
Faster printing

### ISSUE THREAD

**Issue by sven1103** [qbicsoftware/barcode-dragon-portlet#6]
The lpr command is able to print many files much faster using wildcards. the barcode portlet already creates a timestamped folder of each batch of barcodes that are created. the command should be changed to something like lpr [...] timestamp+"/*"

**Comment by sven1103** [comment]
Once portal-testing is up again, we should deploy it there

**Comment by sven1103** [comment]
Ok, merged into development #7

**Comment by Zethson** [comment]
Since this was merged, can this issue be closed?

**Comment by wow-such-code** [comment]
indeed it can
